import { Context } from 'koishi';
export declare class RocomClient {
    private baseUrl;
    private apiKey;
    private timeout;
    constructor(baseUrl: string, apiKey: string, timeout?: number);
    private sanitizeUid;
    private wegameHeaders;
    private rocomHeaders;
    private formatHttpError;
    private isSensitiveLogKey;
    private maskSensitiveValue;
    private sanitizeForLog;
    private headersForLog;
    private stringifyForLog;
    private logRequestFailureDetails;
    private get;
    private post;
    private delete;
    qqQrLogin(ctx: Context, userIdentifier: string): Promise<any>;
    qqQrStatus(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    wechatQrLogin(ctx: Context, userIdentifier: string): Promise<any>;
    wechatQrStatus(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    importToken(ctx: Context, tgpId: string, tgpTicket: string, userIdentifier: string): Promise<any>;
    createBinding(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    refreshBinding(ctx: Context, bindingId: string, userIdentifier: string): Promise<any>;
    deleteBinding(ctx: Context, bindingId: string, userIdentifier: string): Promise<boolean>;
    getRole(ctx: Context, fwToken: string, accountType?: number, userIdentifier?: string): Promise<any>;
    getEvaluation(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getPetSummary(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getCollection(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getBattleOverview(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getBattleList(ctx: Context, fwToken: string, pageSize?: number, afterTime?: string, userIdentifier?: string): Promise<any>;
    private isIngamePlayerPayload;
    ingamePlayerSearch(ctx: Context, uid: string): Promise<any>;
    getPets(ctx: Context, fwToken: string, petSubset?: number, pageNo?: number, pageSize?: number, userIdentifier?: string): Promise<any>;
    getLineupList(ctx: Context, fwToken: string, pageNo?: number, category?: string, userIdentifier?: string): Promise<any>;
    getExchangePosters(ctx: Context, fwToken: string, pageNo?: number, userIdentifier?: string): Promise<any>;
    getMerchantInfo(ctx: Context, refresh?: boolean): Promise<any>;
    queryPetSize(ctx: Context, diameter: number, weight: number): Promise<any>;
    searchWikiPet(ctx: Context, query: string, limit?: number): Promise<any>;
    searchWikiSkill(ctx: Context, query: string, limit?: number): Promise<any>;
}
